sudo: required
services:
  - docker

before_install:
  - docker build -t sivagurunathan/docker-tutorial -f Dockerfile.dev .

script:
  - docker run sivagurunathan/docker-tutorial npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-sample"
  env: "DockerReactSample-env"
  bucket_name: "elasticbeanstalk-us-east-1-537723819007"
  bucket_path: "docker-react-sample"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"